<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.yoyocw</groupId>
        <artifactId>ai-chat-kit-components</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ai-chat-kit-legacy-server</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>AI 智能对话模块接口实现</description>

    <dependencies>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>ai-chat-kit-adapter-hosted-proxy</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>ai-chat-kit-host-platform</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>ai-chat-kit-engine</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>ai-chat-kit-contract</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-env</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>ai-chat-kit-legacy-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-fac-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-biz-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-rpc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yoyocw</groupId>
            <artifactId>platform-compat-starter-monitor</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
