<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         child.project.url.inherit.append.path="false"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>ai-chat-kit</artifactId>
        <groupId>io.github.yoyocw</groupId>
        <version>${revision}</version>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>ai-chat-kit-mcp-jwt</module>
    </modules>

    <profiles>
        <profile>
            <id>platform-compat</id>
            <modules>
                <module>platform-compat-starter-mq</module>
                <module>platform-compat-starter-rpc</module>
                <module>platform-compat-starter-mybatis</module>
                <module>platform-compat-starter-biz-tenant</module>
                <module>platform-compat-starter-web</module>
                <module>platform-compat-starter-redis</module>
                <module>platform-compat-starter-env</module>
                <module>platform-compat-starter-monitor</module>
                <module>platform-compat-starter-job</module>
                <module>platform-compat-starter-security</module>
                <module>platform-compat-common</module>
            </modules>
        </profile>
    </profiles>

    <artifactId>ai-chat-kit-framework</artifactId>
    <description>
        该包是技术组件，每个子包，代表一个组件。每个组件包括两部分：
            1. core 包：是该组件的核心封装
            2. config 包：是该组件基于 Spring 的配置

        技术组件，也分成两类：
            1. 框架组件：和我们熟悉的 MyBatis、Redis 等等的拓展
            2. 业务组件：和业务相关的组件的封装，例如说数据字典、操作日志等等。
        如果是业务组件，Maven 名字会包含 biz
    </description>
    <url>https://github.com/yoyocw/ai-chat-kit</url>

    <scm child.scm.connection.inherit.append.path="false"
         child.scm.developerConnection.inherit.append.path="false"
         child.scm.url.inherit.append.path="false">
        <connection>scm:git:https://github.com/yoyocw/ai-chat-kit.git</connection>
        <developerConnection>scm:git:https://github.com/yoyocw/ai-chat-kit.git</developerConnection>
        <url>https://github.com/yoyocw/ai-chat-kit</url>
        <tag>HEAD</tag>
    </scm>

</project>
